FROM node:22-alpine AS base

# ── deps stage: install all node_modules ─────────────────────────────────────
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --frozen-lockfile

# ── builder stage: generate Prisma + compile Next.js ─────────────────────────
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
# Placeholder DB URL lets Prisma generate the client without a live connection
ENV DATABASE_URL="postgresql://x:x@localhost/x"
ENV DIRECT_URL="postgresql://x:x@localhost/x"

RUN npx prisma generate
RUN npm run build

# ── runner stage: minimal production image ────────────────────────────────────
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=9000
ENV HOSTNAME="0.0.0.0"

RUN apk add --no-cache dumb-init
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Static public files
COPY --from=builder /app/public ./public

# Standalone server output (generated by output: 'standalone')
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Prisma schema + migrations (needed for migrate deploy at startup)
COPY --from=builder /app/prisma ./prisma

# Prisma CLI binary (needed to run `prisma migrate deploy`)
COPY --from=deps /app/node_modules/.bin/prisma ./node_modules/.bin/prisma
COPY --from=deps /app/node_modules/prisma ./node_modules/prisma
COPY --from=deps /app/node_modules/@prisma ./node_modules/@prisma

# Pre-generated Prisma client
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

USER nextjs

EXPOSE 9000

# Run migrations first (idempotent), then start the standalone server
CMD ["dumb-init", "sh", "-c", \
     "node node_modules/prisma/build/index.js migrate deploy && node server.js"]
