# Generated by Django 5.2.15 on 2026-06-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Card hero image', null=True, upload_to='covers/'),
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('favicon_url', models.URLField(blank=True, max_length=2048)),
                ('site_name', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_links', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
