# Generated by Django 5.2.15 on 2026-06-27 16:25

import i18nfield.fields
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikipage_cover_image_sharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='content_de',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full page markdown content', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='content_en',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full page markdown content', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='content_es',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full page markdown content', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='content_fr',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full page markdown content', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='content_uk',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Full page markdown content', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='editorial_notes',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='Per-language editorial notes (django-i18nfield JSON storage)'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_de',
            field=models.TextField(blank=True, help_text='Short preview text for cards and RSS', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_en',
            field=models.TextField(blank=True, help_text='Short preview text for cards and RSS', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_es',
            field=models.TextField(blank=True, help_text='Short preview text for cards and RSS', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_fr',
            field=models.TextField(blank=True, help_text='Short preview text for cards and RSS', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='summary_uk',
            field=models.TextField(blank=True, help_text='Short preview text for cards and RSS', null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_de',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_fr',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='title_uk',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='content_de',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='content_en',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='content_es',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='content_fr',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='content_uk',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikisection',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
