# Generated by Django 5.2.15 on 2026-06-27 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI daily usage',
                'verbose_name_plural': 'AI daily usage',
                'indexes': [models.Index(fields=['user', 'date'], name='ai_aiusaged_user_id_7b6476_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
